// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8lYRLu_S15Lf2GplCp0XRY2kKsxA29Pw',
    appId: '1:682344595366:web:98367c6372746bcccf5967',
    messagingSenderId: '682344595366',
    projectId: 'cvmaker-707de',
    authDomain: 'cvmaker-707de.firebaseapp.com',
    storageBucket: 'cvmaker-707de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdxyT7LcVZMNHwGWUXcUwMq9k52FFpuo8',
    appId: '1:682344595366:android:3f7af9687fc7d51ccf5967',
    messagingSenderId: '682344595366',
    projectId: 'cvmaker-707de',
    storageBucket: 'cvmaker-707de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB94WXPEzFOn-BBd5sbexJ_Q26oLQqhm2M',
    appId: '1:682344595366:ios:abdb411c78b372a0cf5967',
    messagingSenderId: '682344595366',
    projectId: 'cvmaker-707de',
    storageBucket: 'cvmaker-707de.appspot.com',
    iosBundleId: 'com.example.cvmaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB94WXPEzFOn-BBd5sbexJ_Q26oLQqhm2M',
    appId: '1:682344595366:ios:abdb411c78b372a0cf5967',
    messagingSenderId: '682344595366',
    projectId: 'cvmaker-707de',
    storageBucket: 'cvmaker-707de.appspot.com',
    iosBundleId: 'com.example.cvmaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8lYRLu_S15Lf2GplCp0XRY2kKsxA29Pw',
    appId: '1:682344595366:web:6608a2b0303131c2cf5967',
    messagingSenderId: '682344595366',
    projectId: 'cvmaker-707de',
    authDomain: 'cvmaker-707de.firebaseapp.com',
    storageBucket: 'cvmaker-707de.appspot.com',
  );
}
